name: CI-CD

on:
  push:
    branches: ["main"]

permissions:
  contents: write
env:
  IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/hello-cicd

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 1) build e push da imagem
      - name: Build and push Docker image
        run: |
          TAG=${GITHUB_SHA::7}
          docker build -t $IMAGE_NAME:$TAG ./app
          docker push $IMAGE_NAME:$TAG
          echo "TAG=$TAG" >> $GITHUB_ENV

      # 2) puxa o main ANTES de editar o arquivo
      - name: Pull latest main
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main

      # 3) atualiza o deployment com a nova imagem
      - name: Update Kubernetes manifest with new image
        run: |
          sed -i "s|docker.io/.*/hello-cicd:.*|docker.io/${{ secrets.DOCKERHUB_USERNAME }}/hello-cicd:${TAG}|g" k8s/app-deployment.yaml

      # 4) commit e push
      - name: Commit and push manifest changes
        run: |
          git add k8s/app-deployment.yaml
          git commit -m "ci: update image to ${TAG}" || echo "no changes"
          git push
